# Generated by Django 4.0.2 on 2022-03-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allAccounts', '0002_user_accountoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_accounts_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_cinema_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_clubRep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
