# Generated by Django 4.0.2 on 2022-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='tickets',
            field=models.IntegerField(default=0, max_length=300),
        ),
    ]
