# Generated by Django 4.0.3 on 2022-03-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0003_alter_movies_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ticket type')),
                ('price', models.PositiveIntegerField(verbose_name='Ticket price')),
            ],
        ),
    ]
