# Generated by Django 4.0.3 on 2022-03-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0004_ticketdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdiscount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticketdiscount',
            name='price',
        ),
        migrations.AddField(
            model_name='ticketdiscount',
            name='new_price',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='ticketdiscount',
            name='sale_price',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='ticketdiscount',
            name='total_price',
            field=models.IntegerField(default=True),
        ),
    ]
