# Generated by Django 4.0.2 on 2022-04-06 16:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UWE', '0004_ticket_alter_movies_dateandtime_alter_movies_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CinemaManager',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='ClubRep',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='movies',
            name='actor1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='actor2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='actor3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 17, 1, 12, 963073)),
        ),
    ]
