# Generated by Django 4.0.3 on 2022-03-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0005_remove_ticketdiscount_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdiscount',
            name='new_price',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketdiscount',
            name='sale_price',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketdiscount',
            name='total_price',
            field=models.IntegerField(default=False),
        ),
    ]
