# Generated by Django 4.0.2 on 2022-04-06 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0005_delete_cinemamanager_delete_club_delete_clubrep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='ageRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 17, 9, 22, 322997)),
        ),
    ]
