# Generated by Django 4.0.2 on 2022-04-06 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0006_movies_agerating_movies_description_movies_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 17, 19, 23, 243663)),
        ),
    ]
