# Generated by Django 4.0.2 on 2022-04-06 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0007_movies_author_alter_movies_dateandtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('postCode', models.CharField(max_length=10)),
                ('house_num', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('clubRepFirstName', models.CharField(max_length=50)),
                ('clubRepLastName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('clubID', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 17, 26, 53, 373549)),
        ),
    ]
