# Generated by Django 4.0.2 on 2022-04-06 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0008_club_alter_movies_dateandtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='clubRepFirstName',
        ),
        migrations.RemoveField(
            model_name='club',
            name='clubRepLastName',
        ),
        migrations.RemoveField(
            model_name='club',
            name='dob',
        ),
        migrations.AlterField(
            model_name='movies',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 17, 53, 20, 57854)),
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubRepFirstName', models.CharField(max_length=50)),
                ('clubRepLastName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('club_rep_number', models.CharField(max_length=11)),
                ('club_rep_email', models.EmailField(max_length=100, null=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UWE.club')),
            ],
        ),
    ]
