# Generated by Django 4.0.2 on 2022-04-07 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0009_remove_club_clubrepfirstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 10, 59, 29, 156530)),
        ),
        migrations.AlterField(
            model_name='movies',
            name='screen',
            field=models.CharField(blank=True, choices=[('screen1', 'Screen1'), ('screen2', 'Screen2'), ('screen3', 'Screen3'), ('screen4', 'Screen4'), ('screen5', 'Screen5')], max_length=50, null=True),
        ),
    ]
