# Generated by Django 4.0.2 on 2022-04-07 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0010_movies_year_alter_movies_dateandtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='type',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 11, 11, 39, 383874)),
        ),
    ]
