# Generated by Django 4.0.2 on 2022-04-15 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0011_movies_type_alter_movies_dateandtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='movie',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='UWE.movies'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 14, 41, 43, 32075)),
        ),
    ]
